version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install --upgrade 'six~=1.15'
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-rds-dbcluster"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-rds-dbsubnetgroup"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-rds-dbclusterparametergroup"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-rds-eventsubscription"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-rds-globalcluster"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-rds-optiongroup"
      - mvn clean verify --no-transfer-progress
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-rds-dbcluster/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-rds-dbsubnetgroup/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-rds-dbclusterparametergroup/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-rds-eventsubscription/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-rds-globalcluster/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-rds-optiongroup/rpdk.log"
