AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-RDS-DBInstance/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "ec2:DescribeAccountAttributes"
                - "ec2:DescribeAvailabilityZones"
                - "ec2:DescribeInternetGateways"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeVpcAttribute"
                - "ec2:DescribeVpcs"
                - "iam:CreateServiceLinkedRole"
                - "iam:GetRole"
                - "iam:ListRoles"
                - "iam:PassRole"
                - "kms:CreateGrant"
                - "kms:DescribeKey"
                - "rds:AddRoleToDBInstance"
                - "rds:AddTagsToResource"
                - "rds:CreateDBInstance"
                - "rds:CreateDBInstanceReadReplica"
                - "rds:CreateDBSnapshot"
                - "rds:DeleteDBInstance"
                - "rds:DescribeDBClusterSnapshots"
                - "rds:DescribeDBClusters"
                - "rds:DescribeDBEngineVersions"
                - "rds:DescribeDBInstanceAutomatedBackups"
                - "rds:DescribeDBInstances"
                - "rds:DescribeDBParameterGroups"
                - "rds:DescribeDBSnapshots"
                - "rds:DescribeEvents"
                - "rds:ModifyDBInstance"
                - "rds:PromoteReadReplica"
                - "rds:RebootDBInstance"
                - "rds:RemoveRoleFromDBInstance"
                - "rds:RemoveTagsFromResource"
                - "rds:RestoreDBInstanceFromDBSnapshot"
                - "rds:RestoreDBInstanceToPointInTime"
                - "rds:StartDBInstanceAutomatedBackupsReplication"
                - "rds:StopDBInstanceAutomatedBackupsReplication"
                - "secretsmanager:CreateSecret"
                - "secretsmanager:TagResource"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
