repos:
- repo: https://github.com/aws-cloudformation/cfn-python-lint
  rev: v0.61.0  # The version of cfn-lint to use
  hooks:
    - id: cfn-python-lint
      files: contract-test-required-resources.template.yaml
